from langchain.prompts import PromptTemplate

from thinking_hats_ai.hats.hats import Hat, Hats
from thinking_hats_ai.prompting_techniques.base_technique import (
    BasePromptingTechnique,
)

from ..utils.api_handler import APIHandler
from ..utils.brainstorming_input import BrainstormingInput
from ..utils.string_utils import list_to_bulleted_string


class ContrastivePrompting(BasePromptingTechnique):
    """
    A prompting technique that uses contrastive reasoning to refine idea contributions
    by comparing good and bad examples based on a specific thinking hat persona.

    This approach encourages critical evaluation of existing ideas and helps align
    new suggestions more closely with the hat’s values and goals.
    """

    def execute_prompt(
        self,
        brainstorming_input: BrainstormingInput,
        hat: Hat,
        api_handler: APIHandler,
    ):
        """
        Executes a contrastive prompt to analyze and refine brainstorming ideas based on the assigned thinking hat.

        The model:
        - Reviews existing ideas and identifies any misalignment with the hat's perspective.
        - Reflects on contrasting good and bad examples.
        - Produces a revised contribution that better fits the hat's goals without explicitly labeling other ideas.

        Args:
            brainstorming_input (BrainstormingInput): The session's question, current ideas, and response length.
            hat (Hat): The thinking hat perspective to simulate.
            api_handler (APIHandler): API handler to send the prompt and receive a response.

        Returns:
            str: The refined idea generated by the model using contrastive reasoning.
        """
        brainstorming_input.question
        template = PromptTemplate(
            input_variables=[
                "hat_instructions",
                "question",
                "ideas",
                "length",
            ],
            template="Imagine you are wearing a hat with the following instructions: {hat_instructions}\n"
            "This is the brainstorming question: {question}\n"
            "Here are the currently developed ideas:\n{ideas}\n"
            "Contrastive Example:\n"
            "For example, imagine you received a persona like 'you always want to be realistic' for the question 'How can we make a cool birthday party for friends?' Consider these ideas: ['make a karaoke bar', 'have some pizza', 'make a huge party with 10,000 visitors in the White House'].\n"
            "- A GOOD Response might be: 'Let's host a cozy, realistically planned barbeque party at a friend's house.'\n"
            "- A BAD Response might be: 'Let's throw a huge, impractical party in the White House.\n'"
            "- A BAD Response might be: 'I am always realistic, a party in the white house isn't possible\n'"
            "In this example, the good response aligns with the realistic persona while the bad response ignores context and feasibility. Keep this contrast in mind.\n"
            "Your Task: "
            "Using the perspective defined by your current hat, analyze the provided ideas.\n"
            "First, identify if any of the provided ideas include aspects which do not fit to your persona.\n"
            "Explain step-by-step why such ideas are problematic, contrasting them with what would be acceptable or desirable.\n"
            "Finally, propose a revised idea or additional insight that better aligns with your persona’s objectives.\n"
            "Do not say, if you found a bad or good answer. Only respond with your newly generated contribution from your personas hat.\n"
            "Your response should be {length} long.\n",
        )

        prompt = template.format(
            hat_instructions=Hats().get_instructions(hat),
            question=brainstorming_input.question,
            ideas=list_to_bulleted_string(brainstorming_input.ideas),
            length=brainstorming_input.response_length,
        )

        self.logger.start_logger(hat.value)

        self.logger.log_prompt(prompt)

        response = api_handler.get_response(prompt)

        self.logger.log_response(response)

        return response
